modLoader="javafml"
loaderVersion="[32,)"
license="Apache License 2.0"
issueTrackerURL="https://github.com/natanbc/tiletools/issues"
[[mods]]
modId="tiletools"
version="${file.jarVersion}"
displayName="Tile Tools"
#updateJSONURL="http://myurl.me/" # todo
displayURL="https://github.com/natanbc/tiletools"
#logoFile="examplemod.png"        # todo
#credits="Thanks for this example mod goes to Java" 
authors="natanbc"
description='''
A bunch of utilities for dealing with tile entities
'''
[[dependencies.tiletools]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tiletools]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
